from src.service_layer.source_services import *
from src.service_layer.sport_services import *
from src.service_layer.task_services import *
from src.service_layer.user_services import *
from src.service_layer.permission_services import *
from src.service_layer.parameters_services import *
from src.service_layer.config_services import *
from src.service_layer.runs_services import *
from src.service_layer.result_services import *
from src.service_layer.status_services import *
from src.service_layer.custom_match_services import *
# {'status_code', 'detail', 'result'}
