FROM nginx:latest
RUN apt-get update && apt-get install -y wget
RUN wget https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-alpine-linux-amd64-v0.6.1.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-alpine-linux-amd64-v0.6.1.tar.gz \
    && rm dockerize-alpine-linux-amd64-v0.6.1.tar.gz
COPY ./nginx.conf /etc/nginx/nginx.conf
CMD dockerize -wait tcp://frontend_ui:80 -wait tcp://backend_ui:80 -wait tcp://grafana:3000 -timeout 20s && nginx -g 'daemon off;'
